#!/usr/bin/python
# Copyright (C) 2008, Charles Wang <charlesw123456@gmail.com>
# Author: Charles Wang <charlesw123456@gmail.com>
# License: BSD

import sys

from pypi2pkgsys.pypi2packages import pypi2package
from pypi2pkgsys.rpm import pkgsys_rpm as package_system

packager = pypi2package(package_syetem, sys.argv)
packager.run()
