#!/usr/bin/python
# Copyright (C) 2008, Charles Wang <charlesw123456@gmail.com>
# Author: Charles Wang <charlesw123456@gmail.com>
# License: BSD

import sys

from pypi2pkgsys.pypi2packages import pypi2package
from pypi2pkgsys.portage import pkgsys_portage as package_system

packager = pypi2package(package_system, sys.argv)
packager.run()
