#!/usr/bin/python
# Copyright (C) 2008, Charles Wang <charlesw123456@gmail.com>
# Author: Charles Wang <charlesw123456@gmail.com>
# License: BSD

import sys

from pypi2pkgsys.pypi2packages import PYPI2Package
from pypi2pkgsys.dpkg import PkgSysDPkg as PackageSystem

packager = PYPI2Package(PackageSystem, sys.argv)
packager.run()
